[package]
name = "wana_kana"
version = "0.9.0"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
license = "MIT"
keywords = ["japanese", "katakana", "hiragana", "kana", "romaji"]
description = """
Utility library for checking and converting between Japanese characters - Kanji, Hiragana, Katakana - and Romaji
"""

[dependencies]
regex = "0.2"
phf = "0.7.21"
phf_macros = "0.7.21"
lazy_static = "1.0"
itertools = "0.7.6"

[dev-dependencies]
stainless = "0.1.12"